export const SUCCESS = 'SUCCESS';

export const PENDING = 'PENDING';

export const ERROR = 'ERROR';

export const GET_CURRENT_EVENTS_INFO = 'GET_EVENTS_INFO';


export const UPDATE_CLOSEST_EVENT = 'UPDATE_CLOSEST_EVENT';

export const UPDATE_SELECT_EVENT = 'GET_SELECT_EVENT';

//private
export const CLOSEST_FOOD_ADD = 'CLOSEST_FOOD_ADD'; 
export const CLOSEST_FOOD_EDIT = 'CLOSEST_FOOD_EDIT';
export const CLOSEST_FOOD_DELETE = 'CLOSEST_FOOD_DELETE';
export const CLOSEST_GUEST_ADD = 'CLOSEST_GUEST_ADD'; 
export const CLOSEST_GUEST_DELETE = 'CLOSEST_GUEST_DELETE';
export const CLOSEST_INFO_EDIT = 'CLOSEST_INFO_EDIT';
//public
export const CLOSEST_FOOD_SUBMIT = 'CLOSEST_FOOD_SUBMIT';
export const CLOSEST_GUEST_CONFIRM = 'CLOSEST_GUEST_CONFIRM'; 

//private
export const SELECT_FOOD_ADD = 'SELECT_FOOD_ADD';  
export const SELECT_FOOD_EDIT = 'SELECT_FOOD_EDIT';  
export const SELECT_FOOD_DELETE = 'SELECT_FOOD_DELETE'; 
export const SELECT_GUEST_ADD = 'SELECT_GUEST_ADD'; 
export const SELECT_GUEST_DELETE = 'SELECT_GUEST_DELETE'; 
export const SELECT_INFO_EDIT = 'SELECT_INFO_EDIT';
//public
export const SELECT_FOOD_SUBMIT = 'SELECT_FOOD_SUBMIT';
export const SELECT_GUEST_CONFIRM = 'SELECT_GUEST_CONFIRM'; 